// this file auto-generated by sequelize, might be required for migration which done by sequelize-cli.
var fs = require('fs');
var path = require('path');
var sequelize = require('sequelize');
var basename = path.basename(__filename);
var db = {};
var database = require('../helper/database');

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = database['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = database;
db.Sequelize = sequelize;

module.exports = db;
